use crate::settings::{
    asteroids::AsteroidSettings, difficulty::DifficultySettings,
    enemy_evolution::EnemyEvolutionSettings, enemy_expansion::EnemyExpansionSettings,
    map::MapSettings, path_finder::PathFinderSettings, pollution::PollutionSettings,
    steering::SteeringSettings, unit_group::UnitGroupSettings,
};

pub fn mk_default_settings() -> MapSettings<'static> {
    return MapSettings {
        difficulty_settings: DifficultySettings {
            technology_price_multiplier: None,
            spoil_time_modifier: None,
        },
        pollution: PollutionSettings {
            enabled: true,
            comment_min_to_diffuse_1: None,
            comment_min_to_diffuse_2: None,
            diffusion_ratio: None,
            min_to_diffuse: None,
            ageing: None,
            expected_max_per_chunk: None,
            min_to_show_per_chunk: None,
            min_pollution_to_damage_trees: None,
            pollution_with_max_forest_damage: None,
            pollution_restored_per_tree_damage: None,
            pollution_per_tree_damage: None,
            max_pollution_to_restore_trees: None,
            enemy_attack_pollution_consumption_modifier: None,
        },
        steering: SteeringSettings {
            default: None,
            moving: None,
        },
        enemy_evolution: EnemyEvolutionSettings {
            enabled: false,
            time_factor: None,
            destroy_factor: None,
            pollution_factor: None,
        },
        enemy_expansion: EnemyExpansionSettings {
            enabled: false,
            max_expansion_distance: None,
            friendly_base_influence_radius: None,
            enemy_building_influence_radius: None,
            building_coefficient: None,
            other_base_coefficient: None,
            neighbouring_chunk_coefficient: None,
            neighbouring_base_chunk_coefficient: None,
            max_colliding_tiles_coefficient: None,
            settler_group_min_size: None,
            settler_group_max_size: None,
            min_expansion_cooldown: None,
            max_expansion_cooldown: None,
        },
        unit_group: UnitGroupSettings {
            min_group_gathering_time: None,
            max_group_gathering_time: None,
            max_wait_time_for_late_members: None,
            max_group_radius: None,
            min_group_radius: None,
            max_member_speedup_when_behind: None,
            max_member_slowdown_when_ahead: None,
            max_group_slowdown_factor: None,
            max_group_member_fallback_factor: None,
            member_disown_distance: None,
            tick_tolerance_when_member_arrives: None,
            max_gathering_unit_groups: None,
            max_unit_group_size: None,
        },
        path_finder: PathFinderSettings {
            fwd2bwd_ratio: None,
            goal_pressure_ratio: None,
            use_path_cache: false,
            max_steps_worked_per_tick: None,
            max_work_done_per_tick: None,
            short_cache_size: None,
            long_cache_size: None,
            short_cache_min_cacheable_distance: None,
            short_cache_min_algo_steps_to_cache: None,
            long_cache_min_cacheable_distance: None,
            cache_max_connect_to_cache_steps_multiplier: None,
            cache_accept_path_start_distance_ratio: None,
            cache_accept_path_end_distance_ratio: None,
            negative_cache_accept_path_start_distance_ratio: None,
            negative_cache_accept_path_end_distance_ratio: None,
            cache_path_start_distance_rating_multiplier: None,
            cache_path_end_distance_rating_multiplier: None,
            stale_enemy_with_same_destination_collision_penalty: None,
            ignore_moving_enemy_collision_distance: None,
            enemy_with_different_destination_collision_penalty: None,
            general_entity_collision_penalty: None,
            general_entity_subsequent_collision_penalty: None,
            extended_collision_penalty: None,
            max_clients_to_accept_any_new_request: None,
            max_clients_to_accept_short_new_request: None,
            direct_distance_to_consider_short_request: None,
            short_request_max_steps: None,
            short_request_ratio: None,
            min_steps_to_check_path_find_termination: None,
            start_to_goal_cost_multiplier_to_terminate_path_find: None,
            overload_levels: vec![0],
            overload_multipliers: vec![0.0],
            negative_path_cache_delay_interval: None,
        },
        max_failed_behavior_count: None,
        asteroids: AsteroidSettings {
            spawning_rate: None,
            max_ray_portals_expanded_per_tick: None,
        },
    };
}
